### ISSUE TITLE
Can we convert HTML String to Markdown String

### ISSUE THREAD

**Issue by dharamveer-roundr** [JetBrains/markdown#102]
I am looking for a solution where an HTML String can be parsed into MarkDown.
Can we achieve it with this Library?

**Comment by altavir** [comment]
This library obviously parses markdown and generates HTML, not vice versa. You can try using https://pandoc.org/ for generic transofrmations.

Also please note, that in general, markdown covers only very small subset of HTML. Meaning that HTML in general could not be converted to plain markdown.
