### ISSUE TITLE
Tables don't render in Safari

### ISSUE THREAD

**Issue by Leonya** [JetBrains/markdown#117]
This commit https://github.com/JetBrains/markdown/commit/2fdc357bf53d785cc6a567dde92747ef841409bf introduced the following regex: `(?<!\\\\)\\|`, it's not supported in Safari so rendering crashes.

**Comment by FirstTimeInForever** [comment]
Should be fixed in `0.4.1`.

**Comment by Leonya** [comment]
Thanks a lot for such a quick fix!

**Comment by Leonya** [comment]
It's not published yet, right?

**Comment by FirstTimeInForever** [comment]
It will be available in a half an hour at most.
