### ISSUE TITLE
Add math support

### ISSUE THREAD

**Issue by berezhkoE** [JetBrains/markdown#133]
[[IDEA-213075] - Add math support to the markdown plugin](https://youtrack.jetbrains.com/issue/IDEA-213075/Add-math-support-to-the-markdown-plugin)

**Comment by kaesekarl** [comment]
+1

**Comment by ag2s20150909** [comment]
support `\[` and `\]` block math and `\(` and `\(`  inline math

https://gohugo.io/content-management/mathematics/#step-4

**Comment by ko1o** [comment]
+1
