### ISSUE TITLE
GFM Support (PLEASE)

### ISSUE THREAD

**Issue by aidan-gibson** [JetBrains/markdown#144]
Have I gone completely mental or is there no way to highlight text? ie `==text to be highlighted==`.

**Comment by aidan-gibson** [comment]
Okay this was a silly issue to open, I see now this is based on Commonmark spec. Maybe move to GFM?? Or better yet, a WYSIWYG solution? I love using Jetbrains IDEs but this is cringe.

**Comment by boswelja** [comment]
There is GFM support, via `GFMFlavourDescriptor`. I also don't see any mention of highlight in the GFM spec https://github.github.com/gfm/

**Comment by FirstTimeInForever** [comment]
We support GFM via `GFMFlavourDescriptor` - it can be provided to the parser instance on creation.
Indeed, the GFM does not support such elements - you can check this by simply creating a Markdown gist here on GitHub.

If you need support for such feature, you can probably implement it the same way the `org.intellij.markdown.flavours.gfm.StrikeThroughDelimiterParser` is implemented.
