### ISSUE TITLE
Two adjacent links fail to render

### ISSUE THREAD

**Issue by Leonya** [JetBrains/markdown#42]
The following should be rendered as two adjacent links, but instead there's an error:

```
[Rust](https://jetbrains.team/team?team=Rust-MNVpW0Zos2C)[💬](https://jetbrains.team/m/Arseniy.Pendryak)
```

`markdown-it` parser has no problem with this.

**Comment by ajalt** [comment]
This is caused by the `GFMFlavourDescriptor`.

As another example, the following markdown:

```markdown
<i>[1](http://a/b)</i>
```

incorrectly renders as

```html
<i>[1](<a href="http://a/b)&lt;/i&gt;">http://a/b)&lt;/i&gt;</a>
```

rather than 

```html
<i><a href="http://a/b">1</a></i>
```

This is due to the `GFMFlavourDescriptor` incorrectly parsing the content of the link destination as a `GFM_AUTOLINK`:

```
Markdown:PARAGRAPH
  Markdown:HTML_TAG '<i>'
  Markdown:SHORT_REFERENCE_LINK
    Markdown:LINK_LABEL
      Markdown:[ '['
      Markdown:TEXT '1'
      Markdown:] ']'
  Markdown:( '('
  Markdown:GFM_AUTOLINK 'http://a/b)</i>'
```

**Comment by valich** [comment]
I've pushed yet another heuristic, which should fix abovementioned cases. The proper parsing of autolinks along with other inline structures is still not done, not sure it will arrive anytime soon. (though @FirstTimeInForever might help with that at some point of time)
