### ISSUE TITLE
Move off of JCenter / Bintray

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/markdown#64]
From the main readme: `The library is hosted in jcenter and bintray`

See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by sandwwraith** [comment]
+1, migration is needed. This library is used by dokka, and dokka is used for documentation by various core kotlin libraries, like kotlinx.coroutines and kotlinx.serialization

**Comment by valich** [comment]
The move is in progress; the repo was moved under [JetBrains](https://github.com/JetBrains) organization as a consequence.

**Comment by valich** [comment]
First maven-central release was published: https://mvnrepository.com/artifact/org.jetbrains/markdown/0.2.0

It's jvm+js+random set of native targets now, will make proper building for all OSes separately.

Does anybody require some old versions to be published to maven-central? Please respond with the required versions; I'll need to upload them manually.

**Comment by kirill-grouchnikov** [comment]
Dokka 1.4.20 (latest stable) depends on Markdown 0.1.45
