### ISSUE TITLE
Publish to another repository

### ISSUE THREAD

**Issue by CommanderTvis** [JetBrains/markdown#69]
Bintray published version won't be available.

**Comment by jponge** [comment]
+1

`org.jetbrains.dokka:dokka-maven-plugin:1.4.20-dev-65` is on Maven Central, but `org.jetbrains:markdown:jar:0.1.45` is not so the Dokka Maven plugin cannot be used without JCenter.

**Comment by valich** [comment]
0.1.45 is on maven central now: https://mvnrepository.com/artifact/org.jetbrains/markdown/0.1.45
